//
//  ModuleData.swift
//  MatReturnRx
//

import SwiftUI

// ============================================================
// MARK: - Module + Exercise Data
// ============================================================

let mrxModules: [MRXModule] = [
    MRXModule(id: "mob", name: "Mobility / Recovery",
              tagline: "Move better. Recover faster. Stay available.",
              durationMin: 10, durationMax: 15, color: .mrxGreen, isPro: false,
              evidencePanel: "This module uses evidence-informed principles of movement preparation, recovery, symptom monitoring, and progressive loading. MatReturnRx does not diagnose or treat injuries. It supports training readiness and recovery.",
              exercises: [
                  MRXExercise(id: "m1", name: "90/90 Breathing Reset",           sets: 3, reps: "5 breaths",
                              cues: ["Exhale fully before inhaling", "Let ribcage fall on exhale", "No breath-holding"],
                              safetyWarning: "Stop if lightheaded or dizzy. Return to normal breathing."),
                  MRXExercise(id: "m2", name: "Neck Controlled Rotations",        sets: 2, reps: "5 each side",
                              cues: ["Move slow — no forcing", "Stay within pain-free range", "Keep shoulders relaxed"],
                              safetyWarning: "STOP if dizziness, radiating arm symptoms, or severe pain occurs."),
                  MRXExercise(id: "m3", name: "Quadruped Thoracic Rotation",      sets: 2, reps: "8 each side",
                              cues: ["Rotate from mid-back, not lower back", "Follow hand with eyes", "Keep core engaged"],
                              safetyWarning: "Stop if sharp pain in wrist, shoulder, or lower back."),
                  MRXExercise(id: "m4", name: "Scapular Push-Up",                 sets: 2, reps: "10 reps",
                              cues: ["Arms stay straight throughout", "Move only shoulder blades", "Full protract and retract"],
                              safetyWarning: "Stop if shoulder pain, clicking, or instability. Modify to knees if needed."),
                  MRXExercise(id: "m5", name: "90/90 Hip Switch",                 sets: 2, reps: "5 each side",
                              cues: ["Sit tall — don't lean into hip", "Move with control", "Feel the hip joint working"],
                              safetyWarning: "Stop if sharp hip or groin pain. Work only within comfortable range."),
                  MRXExercise(id: "m6", name: "Half-Kneeling Ankle Rocks",        sets: 2, reps: "10 each side",
                              cues: ["Keep heel on floor throughout", "Drive knee over 3rd toe", "Control the motion"],
                              safetyWarning: "Stop if sharp knee or ankle pain."),
                  MRXExercise(id: "m7", name: "Stance Motion Flow",               sets: 2, reps: "30 seconds",
                              cues: ["Stay low — athletic stance", "Move your feet each rep", "Breathe rhythmically"],
                              safetyWarning: "Stop if sharp knee or hip pain. Reduce depth if needed."),
                  MRXExercise(id: "m8", name: "Adductor Rockback",                sets: 2, reps: "8 each side",
                              cues: ["Leg straight out to side", "Rock back slowly", "Keep spine neutral"],
                              safetyWarning: "Stop if sharp groin or hip pain."),
                  MRXExercise(id: "m9", name: "Peanut Ball Thoracic Extension",   sets: 2, reps: "60 sec per level",
                              cues: ["Position at mid-back — not lower back", "Breathe into the stretch", "Move up one vertebra at a time"],
                              safetyWarning: "Do NOT use on lower back or neck. Stop if numbness or tingling occurs."),
              ]),
    MRXModule(id: "kne", name: "Knee Starter",
              tagline: "Build knee control for stance, shots, and scrambles.",
              durationMin: 12, durationMax: 15, color: .mrxOrange, isPro: false,
              evidencePanel: "This module is informed by clinical practice guideline principles for knee ligament sprains and patellofemoral pain, including progressive strengthening, neuromuscular control, and symptom-guided progression.",
              exercises: [
                  MRXExercise(id: "k1", name: "Wall Sit Isometric",              sets: 3, reps: "30 seconds",
                              cues: ["Back flat against wall", "Knees at 90°", "Breathe normally — don't hold breath", "Pain at or below 2/10"],
                              safetyWarning: "Stop if knee pain exceeds 2/10 or increases during the hold."),
                  MRXExercise(id: "k2", name: "Supported Split Squat",           sets: 3, reps: "8 each side",
                              cues: ["3-second descent", "Knee tracks over 2nd toe", "Keep torso upright", "Pain at or below 2/10"],
                              safetyWarning: "Stop if pain exceeds 2/10 or knee feels unstable or gives way."),
                  MRXExercise(id: "k3", name: "Lateral Band Walk",               sets: 3, reps: "12 each direction",
                              cues: ["Band above the knees", "Stay in athletic stance", "Push knees out against band"],
                              safetyWarning: "Stop if knee pain occurs or knee feels unstable."),
                  MRXExercise(id: "k4", name: "Low Step-Down",                   sets: 3, reps: "8 each side",
                              cues: ["3-second eccentric lowering", "Control knee — no cave inward", "Pain at or below 2/10"],
                              safetyWarning: "Stop if pain exceeds 2/10, knee gives way, or you hear/feel a pop."),
              ]),
    MRXModule(id: "nec", name: "Neck Starter",
              tagline: "Build neck control without reckless loading.",
              durationMin: 10, durationMax: 12, color: .mrxPurple, isPro: false,
              evidencePanel: "This module is informed by neck pain clinical practice guideline principles emphasizing screening awareness, mobility, endurance, and referral when symptoms suggest higher risk.",
              exercises: [
                  MRXExercise(id: "n1", name: "Seated Chin Tuck",                sets: 3, reps: "10 reps × 5 sec hold",
                              cues: ["Pull chin straight back — create a double chin", "Hold 5 seconds", "Keep jaw relaxed", "Breathe normally"],
                              safetyWarning: "Stop if dizziness, headache, or radiating arm symptoms occur."),
                  MRXExercise(id: "n2", name: "Supine Deep Neck Flexor Hold",    sets: 3, reps: "10 second holds",
                              cues: ["Lie on back, knees bent", "Perform chin tuck first", "Lift head 1-2 inches only", "Hold without shaking or strain"],
                              safetyWarning: "Stop immediately if dizziness, headache, or radiating arm symptoms."),
                  MRXExercise(id: "n3", name: "Four-Way Neck Isometrics",        sets: 2, reps: "5 each direction × 10 sec",
                              cues: ["30% effort only to start", "Push into hand — do not let head move", "Breathe throughout", "4 directions: front, back, each side"],
                              safetyWarning: "STOP if radiating arm pain, dizziness, severe headache, or numbness/tingling."),
                  MRXExercise(id: "n4", name: "Quadruped Neck Control",          sets: 2, reps: "30 seconds",
                              cues: ["Hands and knees position", "Pack chin — maintain neutral neck", "Hold without letting head drop", "Breathe normally throughout"],
                              safetyWarning: "Stop if radiating symptoms, dizziness, or significant neck strain."),
              ]),
    MRXModule(id: "sho", name: "Shoulder Starter",
              tagline: "Build shoulder control for contact positions.",
              durationMin: 12, durationMax: 15, color: .mrxTeal, isPro: false,
              evidencePanel: "This module is informed by evidence-based shoulder rehabilitation principles emphasizing active exercise, scapular control, rotator cuff capacity, symptom monitoring, and referral when instability or neurological symptoms are present.",
              exercises: [
                  MRXExercise(id: "s1", name: "Scapular Push-Up",                sets: 3, reps: "12 reps",
                              cues: ["Arms stay straight throughout", "Move only the shoulder blades", "Full protraction and full retraction", "Slow and controlled"],
                              safetyWarning: "Stop if shoulder pain, clicking, or instability. Perform from knees if needed."),
                  MRXExercise(id: "s2", name: "Quadruped Shoulder Taps",          sets: 3, reps: "10 each side",
                              cues: ["Minimize rotation during each tap", "Pack shoulder blades down and back", "Move slowly and with control", "Breathe normally"],
                              safetyWarning: "Stop if shoulder feels unstable, painful, or like it might slip."),
                  MRXExercise(id: "s3", name: "Band External Rotation",           sets: 3, reps: "15 each side",
                              cues: ["Elbow at 90° against body", "Rotate outward — don't shrug", "Control the return slowly", "Use light resistance to start"],
                              safetyWarning: "Stop if pain above 2/10, instability, or numbness/tingling into arm."),
                  MRXExercise(id: "s4", name: "Serratus Wall Slide",              sets: 3, reps: "10 reps",
                              cues: ["Forearms on wall, elbows at shoulder height", "Drive arms up — push wall away", "Feel shoulder blades spread on upslide", "Keep ribs down"],
                              safetyWarning: "Stop if shoulder pain increases or instability appears during the movement."),
              ]),

    MRXModule(id: "hip", name: "Hip & Groin Injury Prevention",
              tagline: "Restore hip control for explosive shots and scrambles.",
              durationMin: 12, durationMax: 16, color: .mrxYellow, isPro: false,
              evidencePanel: "This module applies evidence-informed principles for adductor and hip flexor rehabilitation in athletes, emphasizing isometric loading, progressive strengthening, and pain-guided progression. It does not diagnose or treat injury.",
              exercises: [
                  MRXExercise(id: "h1", name: "Standing Hip Circle",              sets: 2, reps: "10 each direction",
                              cues: ["Stand on one leg — hold wall for balance", "Draw slow controlled circles with your hip", "Full range if pain-free"],
                              safetyWarning: "Stop if sharp groin or hip pain. Hold wall for balance as needed."),
                  MRXExercise(id: "h2", name: "Side-Lying Hip Abduction",         sets: 3, reps: "15 each side",
                              cues: ["Lie on side, bottom knee slightly bent", "Top leg straight, toes slightly rotated down", "Lift to hip height — no higher", "Keep pelvis stacked throughout"],
                              safetyWarning: "Stop if hip or groin pain exceeds 2/10."),
                  MRXExercise(id: "h3", name: "Copenhagen Adductor Hold",         sets: 3, reps: "20 sec each side",
                              cues: ["Side plank with top leg on bench or chair", "Bottom leg hovering or lightly supported", "Hold — do not let hip sag", "Pain at or below 2/10 throughout"],
                              safetyWarning: "Stop if sharp groin pain or hip instability. Regress to supported version with bottom foot on floor."),
                  MRXExercise(id: "h4", name: "Posterior Hip Capsule Stretch",    sets: 2, reps: "45 sec each side",
                              cues: ["Lie on side — stack hips directly on top of each other", "Use top hand to gently press wrist toward floor", "Stay within a comfortable stretch range", "Do not force range"],
                              safetyWarning: "Stop if sharp hip or shoulder pain. This targets the posterior hip — do not overpress."),
              ]),

    MRXModule(id: "lbk", name: "Lower Back Injury Prevention",
              tagline: "Build the core foundation that protects every takedown.",
              durationMin: 12, durationMax: 15, color: Color(red: 0.4, green: 0.78, blue: 0.55), isPro: false,
              evidencePanel: "This module follows clinical guideline principles for non-specific low back pain, including motor control exercises, progressive loading, and symptom-guided progression. Seek professional evaluation if symptoms are severe, worsening, or include radiating leg pain.",
              exercises: [
                  MRXExercise(id: "l1", name: "Dead Bug",                          sets: 3, reps: "8 each side",
                              cues: ["Press lower back firmly into floor — maintain throughout", "Exhale as you extend opposite arm and leg", "Move slowly — control the entire range", "No arching — spine stays neutral"],
                              safetyWarning: "Stop if lower back pain exceeds 2/10 or if leg symptoms appear."),
                  MRXExercise(id: "l2", name: "Bird Dog",                           sets: 3, reps: "10 each side",
                              cues: ["Hands and knees — neutral spine", "Extend opposite arm and leg simultaneously", "Hold 2 seconds at full extension", "Keep hips level — no rotation allowed"],
                              safetyWarning: "Stop if sharp lower back pain, hip pain, or leg symptoms appear."),
                  MRXExercise(id: "l3", name: "Glute Bridge Hold",                  sets: 3, reps: "10 × 3 sec hold",
                              cues: ["Feet flat, knees bent to 90°", "Drive through heels — squeeze glutes at top", "Hold 3 seconds — don't let hips drop", "Keep ribs down — no lumbar hyperextension"],
                              safetyWarning: "Stop if lower back pain or buttock/leg symptoms appear."),
                  MRXExercise(id: "l4", name: "McGill Side Plank (Short)",          sets: 2, reps: "20 sec each side",
                              cues: ["Elbow under shoulder, knees bent", "Lift hips — create straight line from shoulder to knees", "Hold without holding your breath", "Don't sag — maintain the position"],
                              safetyWarning: "Stop if lower back, hip, or shoulder pain exceeds 2/10."),
              ]),

    // ── PRO · PERFORMANCE ───────────────────────────────────────
    MRXModule(id: "grp", name: "Grappling Strength Foundation",
              tagline: "Build the strength base every combat athlete needs.",
              durationMin: 15, durationMax: 20, color: .mrxBlue, isPro: true,
              evidencePanel: "This module applies sport-specific strength training principles for combat athletes, including isometric loading, anti-rotation core work, posterior chain development, and grip endurance. All loading is symptom-guided.",
              exercises: [
                  MRXExercise(id: "g1", name: "Isometric Towel Row Hold",          sets: 3, reps: "10 sec × 3 per side",
                              cues: ["Loop towel around anchor at hip height", "Grip hard — pull and hold isometrically", "Drive elbow back — squeeze shoulder blade", "Breathe throughout — do not hold breath"],
                              safetyWarning: "Stop if shoulder, elbow, or wrist pain exceeds 2/10."),
                  MRXExercise(id: "g2", name: "Push-Up with Serratus Plus",        sets: 3, reps: "10 reps",
                              cues: ["Full push-up", "At top — add extra push to protract shoulder blades", "Control the descent — 3 seconds down", "Keep core tight — no sagging hips"],
                              safetyWarning: "Stop if shoulder pain, wrist pain, or instability appears. Modify to knees if needed."),
                  MRXExercise(id: "g3", name: "Bulgarian Split Squat",             sets: 3, reps: "8 each side",
                              cues: ["Rear foot elevated on bench or chair", "Front shin stays vertical on descent", "Drive through front heel on ascent", "Upright torso — control full range"],
                              safetyWarning: "Stop if knee pain exceeds 2/10, knee feels unstable, or sharp hip flexor pain."),
                  MRXExercise(id: "g4", name: "Farmer Carry",                      sets: 3, reps: "30 sec per set",
                              cues: ["Heavy load in each hand — start moderate", "Stand tall — don't lean to either side", "Grip hard throughout entire carry", "Breathe rhythmically — controlled pace"],
                              safetyWarning: "Stop if wrist, elbow, or shoulder pain appears. Start light and build progressively."),
                  MRXExercise(id: "g5", name: "Neck Plank (Supported Iso)",        sets: 2, reps: "15 sec each direction",
                              cues: ["Lying prone — forehead on folded towel", "Gently lift head 1 inch only", "Hold without straining", "Keep neck long — no chin jutting"],
                              safetyWarning: "Stop immediately if dizziness, radiating arm symptoms, or headache. Seek medical evaluation before continuing."),
              ]),

    // ── PRO · RETURN TO SPORT ───────────────────────────────────
    MRXModule(id: "rtm", name: "Return to Mat Protocol",
              tagline: "Progressive return to grappling — safe and structured.",
              durationMin: 15, durationMax: 20, color: .mrxDanger, isPro: true,
              evidencePanel: "Return-to-sport decisions require clearance from a qualified healthcare professional. This module supports progressive movement reintegration using sport-specific patterns but does NOT provide medical clearance. Do not use this module if you have not been evaluated for your injury.",
              exercises: [
                  MRXExercise(id: "r1", name: "Controlled Pummeling Pattern",      sets: 3, reps: "30 seconds",
                              cues: ["Athletic stance — controlled pace", "Mimic pummeling motion without contact or resistance", "Monitor pain level after each set", "Stop if pain reaches 2/10"],
                              safetyWarning: "Only perform when cleared by your healthcare provider. Stop if any pain, instability, or symptom increase."),
                  MRXExercise(id: "r2", name: "Single-Leg Balance Reach",          sets: 3, reps: "30 sec each side",
                              cues: ["Stand on one leg", "Reach opposite foot forward, side, then behind", "Control through each reach — don't rush", "Monitor joint confidence throughout"],
                              safetyWarning: "Stop if sharp pain, giving-way sensation, or instability. Seek clearance before returning to live training."),
                  MRXExercise(id: "r3", name: "Level-Change Drill",                sets: 3, reps: "8 reps",
                              cues: ["Start upright — lower into wrestling level-change position", "Return to standing with full control", "Simulate wrestling level change — no contact", "Movement quality only — not speed"],
                              safetyWarning: "Perform on padded surface. Stop if knee, hip, or back pain exceeds 2/10."),
                  MRXExercise(id: "r4", name: "Stance and Step Pattern",           sets: 3, reps: "45 seconds",
                              cues: ["Athletic stance", "Step laterally two steps each direction", "Add direction changes every 10 seconds", "Monitor how your body responds to sport-specific demands"],
                              safetyWarning: "Stop if pain increases, joint feels unstable, or you feel unready to continue. This is not a return-to-sport clearance — consult your PT or sports medicine provider."),
              ]),
]
